# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 583)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/tf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 40, 80, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(145, 40, 260, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 120, 25))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 75, 80, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 75, 100, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 95, 110, 20))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 120, 480, 131))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 310, 100, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 380, 120, 25))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(135, 380, 271, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(420, 380, 80, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 450, 71, 20))
        self.label_4.setObjectName("label_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(379, 420, 111, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 480, 480, 50))
        self.textEdit_2.setObjectName("textEdit_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 280, 481, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 260, 120, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 350, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 310, 100, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 516, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionLearningRate = QtWidgets.QAction(MainWindow)
        self.actionLearningRate.setObjectName("actionLearningRate")
        self.actionBatchSize = QtWidgets.QAction(MainWindow)
        self.actionBatchSize.setObjectName("actionBatchSize")
        self.actionTraining_Steps = QtWidgets.QAction(MainWindow)
        self.actionTraining_Steps.setObjectName("actionTraining_Steps")
        self.actionValidation_Percentage = QtWidgets.QAction(MainWindow)
        self.actionValidation_Percentage.setObjectName("actionValidation_Percentage")
        self.actionTesing_Percentage = QtWidgets.QAction(MainWindow)
        self.actionTesing_Percentage.setObjectName("actionTesing_Percentage")
        self.actionRead_Me = QtWidgets.QAction(MainWindow)
        self.actionRead_Me.setObjectName("actionRead_Me")
        self.actionStart_Training = QtWidgets.QAction(MainWindow)
        self.actionStart_Training.setObjectName("actionStart_Training")
        self.actionStart_Testing = QtWidgets.QAction(MainWindow)
        self.actionStart_Testing.setObjectName("actionStart_Testing")
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionContact_Author = QtWidgets.QAction(MainWindow)
        self.actionContact_Author.setObjectName("actionContact_Author")
        self.actionRead_Me_2 = QtWidgets.QAction(MainWindow)
        self.actionRead_Me_2.setObjectName("actionRead_Me_2")
        self.menuHelp.addAction(self.actionRead_Me_2)
        self.menuHelp.addAction(self.actionContact_Author)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ImagePredict"))
        self.pushButton_2.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "ImageSet Location:"))
        self.pushButton.setText(_translate("MainWindow", "Settings..."))
        self.pushButton_3.setText(_translate("MainWindow", "Start Training"))
        self.label_2.setText(_translate("MainWindow", "Training Status:"))
        self.pushButton_4.setText(_translate("MainWindow", "Save Results"))
        self.label_3.setText(_translate("MainWindow", "Select an image:"))
        self.pushButton_7.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Prediction:"))
        self.pushButton_8.setText(_translate("MainWindow", "Start Prediction"))
        self.label_5.setText(_translate("MainWindow", "Training Process:"))
        self.label_6.setText(_translate("MainWindow", "Please choose a folder as the image set:"))
        self.label_7.setText(_translate("MainWindow", "Please choose an image to make a prediction:"))
        self.pushButton_5.setText(_translate("MainWindow", "Delete Model"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionLearningRate.setText(_translate("MainWindow", "Learning Rate"))
        self.actionBatchSize.setText(_translate("MainWindow", "Batch Size"))
        self.actionTraining_Steps.setText(_translate("MainWindow", "Training Steps"))
        self.actionValidation_Percentage.setText(_translate("MainWindow", "Validation Percentage"))
        self.actionTesing_Percentage.setText(_translate("MainWindow", "Tesing Percentage"))
        self.actionRead_Me.setText(_translate("MainWindow", "Read Me"))
        self.actionStart_Training.setText(_translate("MainWindow", "Start Training"))
        self.actionStart_Testing.setText(_translate("MainWindow", "Start Testing"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "Open Folder"))
        self.actionSave.setText(_translate("MainWindow", "Save Results"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionContact_Author.setText(_translate("MainWindow", "Contact Author..."))
        self.actionRead_Me_2.setText(_translate("MainWindow", "Read Me..."))

