# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 30, 80, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(145, 30, 260, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 120, 25))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 60, 80, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 60, 100, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 110, 20))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 110, 480, 150))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 270, 101, 22))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 270, 80, 22))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 270, 80, 22))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 320, 120, 25))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(135, 320, 271, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(420, 320, 80, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 370, 71, 20))
        self.label_4.setObjectName("label_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(390, 350, 100, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 390, 480, 50))
        self.textEdit_2.setObjectName("textEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionLearningRate = QtWidgets.QAction(MainWindow)
        self.actionLearningRate.setObjectName("actionLearningRate")
        self.actionBatchSize = QtWidgets.QAction(MainWindow)
        self.actionBatchSize.setObjectName("actionBatchSize")
        self.actionTraining_Steps = QtWidgets.QAction(MainWindow)
        self.actionTraining_Steps.setObjectName("actionTraining_Steps")
        self.actionValidation_Percentage = QtWidgets.QAction(MainWindow)
        self.actionValidation_Percentage.setObjectName("actionValidation_Percentage")
        self.actionTesing_Percentage = QtWidgets.QAction(MainWindow)
        self.actionTesing_Percentage.setObjectName("actionTesing_Percentage")
        self.actionRead_Me = QtWidgets.QAction(MainWindow)
        self.actionRead_Me.setObjectName("actionRead_Me")
        self.actionStart_Training = QtWidgets.QAction(MainWindow)
        self.actionStart_Training.setObjectName("actionStart_Training")
        self.actionStart_Testing = QtWidgets.QAction(MainWindow)
        self.actionStart_Testing.setObjectName("actionStart_Testing")
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "ImageSet Location:"))
        self.pushButton.setText(_translate("MainWindow", "Settings..."))
        self.pushButton_3.setText(_translate("MainWindow", "Start Training"))
        self.label_2.setText(_translate("MainWindow", "Training Status:"))
        self.pushButton_4.setText(_translate("MainWindow", "Save Results"))
        self.pushButton_5.setText(_translate("MainWindow", "Reset"))
        self.pushButton_6.setText(_translate("MainWindow", "Delete..."))
        self.label_3.setText(_translate("MainWindow", "Select an image:"))
        self.pushButton_7.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Prediction:"))
        self.pushButton_8.setText(_translate("MainWindow", "Start Testing"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionLearningRate.setText(_translate("MainWindow", "Learning Rate"))
        self.actionBatchSize.setText(_translate("MainWindow", "Batch Size"))
        self.actionTraining_Steps.setText(_translate("MainWindow", "Training Steps"))
        self.actionValidation_Percentage.setText(_translate("MainWindow", "Validation Percentage"))
        self.actionTesing_Percentage.setText(_translate("MainWindow", "Tesing Percentage"))
        self.actionRead_Me.setText(_translate("MainWindow", "Read Me"))
        self.actionStart_Training.setText(_translate("MainWindow", "Start Training"))
        self.actionStart_Testing.setText(_translate("MainWindow", "Start Testing"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "Open Folder"))
        self.actionSave.setText(_translate("MainWindow", "Save Results"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))

