# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(520, 460))
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/tf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.MainWidget = QtWidgets.QWidget(MainWindow)
        self.MainWidget.setObjectName("MainWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.MainWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 520, 440))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab{width:120}\n"
"QTabBar::tab{height:20}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.Train = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Train.setFont(font)
        self.Train.setObjectName("Train")
        self.SelFolderTip = QtWidgets.QLabel(self.Train)
        self.SelFolderTip.setGeometry(QtCore.QRect(20, 15, 480, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SelFolderTip.setFont(font)
        self.SelFolderTip.setTextFormat(QtCore.Qt.AutoText)
        self.SelFolderTip.setObjectName("SelFolderTip")
        self.ImageSetLocLabel = QtWidgets.QLabel(self.Train)
        self.ImageSetLocLabel.setGeometry(QtCore.QRect(20, 60, 120, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ImageSetLocLabel.setFont(font)
        self.ImageSetLocLabel.setObjectName("ImageSetLocLabel")
        self.ImageSetPath = QtWidgets.QLineEdit(self.Train)
        self.ImageSetPath.setGeometry(QtCore.QRect(140, 60, 260, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ImageSetPath.setFont(font)
        self.ImageSetPath.setObjectName("ImageSetPath")
        self.ImageSetBrowseButton = QtWidgets.QPushButton(self.Train)
        self.ImageSetBrowseButton.setGeometry(QtCore.QRect(420, 60, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ImageSetBrowseButton.setFont(font)
        self.ImageSetBrowseButton.setObjectName("ImageSetBrowseButton")
        self.SettingsButton = QtWidgets.QPushButton(self.Train)
        self.SettingsButton.setGeometry(QtCore.QRect(310, 100, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.SettingsButton.setFont(font)
        self.SettingsButton.setObjectName("SettingsButton")
        self.StartTrainingButton = QtWidgets.QPushButton(self.Train)
        self.StartTrainingButton.setGeometry(QtCore.QRect(400, 100, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.StartTrainingButton.setFont(font)
        self.StartTrainingButton.setObjectName("StartTrainingButton")
        self.TrainingStatusLabel = QtWidgets.QLabel(self.Train)
        self.TrainingStatusLabel.setGeometry(QtCore.QRect(20, 130, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.TrainingStatusLabel.setFont(font)
        self.TrainingStatusLabel.setObjectName("TrainingStatusLabel")
        self.TrainingStatusBrowser = QtWidgets.QTextBrowser(self.Train)
        self.TrainingStatusBrowser.setGeometry(QtCore.QRect(20, 160, 480, 135))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.TrainingStatusBrowser.setFont(font)
        self.TrainingStatusBrowser.setObjectName("TrainingStatusBrowser")
        self.ProgressLabel = QtWidgets.QLabel(self.Train)
        self.ProgressLabel.setGeometry(QtCore.QRect(20, 300, 120, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ProgressLabel.setFont(font)
        self.ProgressLabel.setObjectName("ProgressLabel")
        self.progressBar = QtWidgets.QProgressBar(self.Train)
        self.progressBar.setGeometry(QtCore.QRect(20, 330, 480, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.DelModelButton = QtWidgets.QPushButton(self.Train)
        self.DelModelButton.setGeometry(QtCore.QRect(280, 370, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.DelModelButton.setFont(font)
        self.DelModelButton.setObjectName("DelModelButton")
        self.SaveResButton = QtWidgets.QPushButton(self.Train)
        self.SaveResButton.setGeometry(QtCore.QRect(400, 370, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.SaveResButton.setFont(font)
        self.SaveResButton.setObjectName("SaveResButton")
        self.LoadConfigButton = QtWidgets.QPushButton(self.Train)
        self.LoadConfigButton.setGeometry(QtCore.QRect(220, 100, 80, 25))
        self.LoadConfigButton.setObjectName("LoadConfigButton")
        self.tabWidget.addTab(self.Train, "")
        self.Predict = QtWidgets.QWidget()
        self.Predict.setObjectName("Predict")
        self.SelImgTipLabel = QtWidgets.QLabel(self.Predict)
        self.SelImgTipLabel.setGeometry(QtCore.QRect(20, 20, 380, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SelImgTipLabel.setFont(font)
        self.SelImgTipLabel.setObjectName("SelImgTipLabel")
        self.SelImgLabel = QtWidgets.QLabel(self.Predict)
        self.SelImgLabel.setGeometry(QtCore.QRect(20, 70, 120, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.SelImgLabel.setFont(font)
        self.SelImgLabel.setObjectName("SelImgLabel")
        self.PredictResBrowser = QtWidgets.QTextBrowser(self.Predict)
        self.PredictResBrowser.setGeometry(QtCore.QRect(20, 190, 480, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.PredictResBrowser.setFont(font)
        self.PredictResBrowser.setObjectName("PredictResBrowser")
        self.PredictResLabel = QtWidgets.QLabel(self.Predict)
        self.PredictResLabel.setGeometry(QtCore.QRect(20, 150, 120, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.PredictResLabel.setFont(font)
        self.PredictResLabel.setObjectName("PredictResLabel")
        self.QWRLabel = QtWidgets.QLabel(self.Predict)
        self.QWRLabel.setGeometry(QtCore.QRect(80, 300, 180, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.QWRLabel.setFont(font)
        self.QWRLabel.setObjectName("QWRLabel")
        self.WrongButton = QtWidgets.QPushButton(self.Predict)
        self.WrongButton.setGeometry(QtCore.QRect(300, 300, 75, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.WrongButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/Wrong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WrongButton.setIcon(icon1)
        self.WrongButton.setObjectName("WrongButton")
        self.RightButton = QtWidgets.QPushButton(self.Predict)
        self.RightButton.setGeometry(QtCore.QRect(400, 300, 75, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.RightButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/Right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RightButton.setIcon(icon2)
        self.RightButton.setObjectName("RightButton")
        self.ImagePath = QtWidgets.QLineEdit(self.Predict)
        self.ImagePath.setGeometry(QtCore.QRect(130, 70, 271, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ImagePath.setFont(font)
        self.ImagePath.setObjectName("ImagePath")
        self.ImageBrowseButton = QtWidgets.QPushButton(self.Predict)
        self.ImageBrowseButton.setGeometry(QtCore.QRect(420, 70, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ImageBrowseButton.setFont(font)
        self.ImageBrowseButton.setObjectName("ImageBrowseButton")
        self.StartPredictButton = QtWidgets.QPushButton(self.Predict)
        self.StartPredictButton.setGeometry(QtCore.QRect(380, 120, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.StartPredictButton.setFont(font)
        self.StartPredictButton.setObjectName("StartPredictButton")
        self.tabWidget.addTab(self.Predict, "")
        MainWindow.setCentralWidget(self.MainWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 520, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionLearningRate = QtWidgets.QAction(MainWindow)
        self.actionLearningRate.setObjectName("actionLearningRate")
        self.actionBatchSize = QtWidgets.QAction(MainWindow)
        self.actionBatchSize.setObjectName("actionBatchSize")
        self.actionTraining_Steps = QtWidgets.QAction(MainWindow)
        self.actionTraining_Steps.setObjectName("actionTraining_Steps")
        self.actionValidation_Percentage = QtWidgets.QAction(MainWindow)
        self.actionValidation_Percentage.setObjectName("actionValidation_Percentage")
        self.actionTesing_Percentage = QtWidgets.QAction(MainWindow)
        self.actionTesing_Percentage.setObjectName("actionTesing_Percentage")
        self.actionRead_Me = QtWidgets.QAction(MainWindow)
        self.actionRead_Me.setObjectName("actionRead_Me")
        self.actionStart_Training = QtWidgets.QAction(MainWindow)
        self.actionStart_Training.setObjectName("actionStart_Training")
        self.actionStart_Testing = QtWidgets.QAction(MainWindow)
        self.actionStart_Testing.setObjectName("actionStart_Testing")
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionContact_Author = QtWidgets.QAction(MainWindow)
        self.actionContact_Author.setObjectName("actionContact_Author")
        self.actionRead_Me_2 = QtWidgets.QAction(MainWindow)
        self.actionRead_Me_2.setObjectName("actionRead_Me_2")
        self.menuHelp.addAction(self.actionRead_Me_2)
        self.menuHelp.addAction(self.actionContact_Author)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ImagePredict"))
        self.SelFolderTip.setText(_translate("MainWindow", "Before starting, please choose a folder as the image set and \n"
"load your configure file:"))
        self.ImageSetLocLabel.setText(_translate("MainWindow", "ImageSet Location:"))
        self.ImageSetBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.SettingsButton.setText(_translate("MainWindow", " Settings..."))
        self.StartTrainingButton.setText(_translate("MainWindow", "Start Training"))
        self.TrainingStatusLabel.setText(_translate("MainWindow", "Training Status:"))
        self.ProgressLabel.setText(_translate("MainWindow", "Training Process:"))
        self.DelModelButton.setText(_translate("MainWindow", "Delete Model"))
        self.SaveResButton.setText(_translate("MainWindow", "Save Results"))
        self.LoadConfigButton.setText(_translate("MainWindow", "Load..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Train), _translate("MainWindow", "Train"))
        self.SelImgTipLabel.setText(_translate("MainWindow", "Please choose an image to make a prediction:"))
        self.SelImgLabel.setText(_translate("MainWindow", "Select an image:"))
        self.PredictResLabel.setText(_translate("MainWindow", "Prediction  Result:"))
        self.QWRLabel.setText(_translate("MainWindow", "   Is this prediction right?"))
        self.WrongButton.setText(_translate("MainWindow", "Wrong"))
        self.RightButton.setText(_translate("MainWindow", "Right"))
        self.ImageBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.StartPredictButton.setText(_translate("MainWindow", "Start Prediction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Predict), _translate("MainWindow", "Predict"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionLearningRate.setText(_translate("MainWindow", "Learning Rate"))
        self.actionBatchSize.setText(_translate("MainWindow", "Batch Size"))
        self.actionTraining_Steps.setText(_translate("MainWindow", "Training Steps"))
        self.actionValidation_Percentage.setText(_translate("MainWindow", "Validation Percentage"))
        self.actionTesing_Percentage.setText(_translate("MainWindow", "Tesing Percentage"))
        self.actionRead_Me.setText(_translate("MainWindow", "Read Me"))
        self.actionStart_Training.setText(_translate("MainWindow", "Start Training"))
        self.actionStart_Testing.setText(_translate("MainWindow", "Start Testing"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "Open Folder"))
        self.actionSave.setText(_translate("MainWindow", "Save Results"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionContact_Author.setText(_translate("MainWindow", "Contact Author..."))
        self.actionRead_Me_2.setText(_translate("MainWindow", "Read Me..."))

